name: PHP Docker CI/CD

on:
  push:
    branches: [main]

env:
  IMAGE_NAME: localhost:5001/phpapp

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker registry
      uses: docker/login-action@v3
      with:
        registry: localhost:5000
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ env.IMAGE_NAME }}:latest

    - name: Deploy container (example via SSH)
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          docker pull ${{ env.IMAGE_NAME }}:latest
          docker stop phpapp || true
          docker rm phpapp || true
          docker run -d --name phpapp -p 80:80 ${{ env.IMAGE_NAME }}:latest

